### ISSUE TITLE
Provide an API to configure automatic session token refresh

### ISSUE THREAD

**Issue by kprav33n** [datacenter/pyaci#16]
APIC sessions do timeout. The timeout is indicated in the response to the login request. Track the timeout, and issue auto refresh at say about 60% of the indicated timeout.

**Comment by kprav33n** [comment]
Requesting ideas from @amney @agccie @arunksaha

**Comment by arunksaha** [comment]
How long is the default timeout? Does the client have an option for a longer timeout?

**Comment by agccie** [comment]
Default timeout is 300 seconds but this is configured within APIC fabric policy.  The timeout value is returned in successfully login post 'refreshTimeoutSeconds'
