### ISSUE TITLE
How to add childern to a MO object? 

### ISSUE THREAD

**Issue by the-modern-leo** [datacenter/pyaci#43]
How do i get an object with a direct call, and than add it's childern after? 

Should look something like this:

#get a direct epg
epg_request = apic.mit.polUni().fvTenant(tenant_name).fvAp(app_name).fvAEPg(epg_name).GET()[0]
#add the childern of that EPG
epg_request.GET(**options.subtree)

**Comment by kprav33n** [comment]
If you want to get the entire subtree (recursive) of an EPG, you can do the following:

```python

**Comment by the-modern-leo** [comment]
Wonderful. That is pretty helpful.
