### ISSUE TITLE
How to use ResolveClass with subtreeClass

### ISSUE THREAD

**Issue by camrossi** [datacenter/pyaci#55]
I am trying to get the lldp neighbours on an interface. 

Initially I tried to do this:
`lldp_neighbours = apic.methods.ResolveClass('lldpIf').GET(**options.filter(filters.Eq('lldpIf.portDesc',path.tDn)) & options.subtreeClass('lldpAdjEp') ) `
 But this does not work and I am not getting anything back no `lldpIf` nor `lldpAdjEp`.

As a work around I did:

`lldp_neighbours = apic.methods.ResolveClass('lldpIf').GET(**options.filter(filters.Eq('lldpIf.portDesc',path.tDn)) & options.rspSubtreeChildren )`

This works fine and I can then just access the `ldp_neighbour.lldpAdjEp` instance but can't understand why the first option does not work. In this case is not a big issue as there aren't that many child of lldpIf but I would like to understand how you should this be done.

**Comment by kprav33n** [comment]
These options are passed on to the server using the URL constructed. Please look at the query filters section in [this documentation](https://www.cisco.com/c/en/us/td/docs/switches/datacenter/aci/apic/sw/2-x/rest_cfg/2_1_x/b_Cisco_APIC_REST_API_Configuration_Guide/b_Cisco_APIC_REST_API_Configuration_Guide_chapter_01.html). IIRC, `subtreeClass` is applicable only when you are using it with `rspSubtreeFull` or `rspSubtreeChildren`. Please turn on logging to see the corresponding REST API requests it is making.

```python
import logging
logging.basicConfig(level=logging.INFO)
logging.getLogger('pyaci').setLevel(logging.DEBUG)
```

**Comment by camrossi** [comment]
I see, thanks the logging was also very helpful :)

Like this works
```
lldp_neighbours = apic.methods.ResolveClass('lldpIf').GET(**options.filter(
filters.Eq('lldpIf.portDesc',path.tDn)) & 
options.rspSubtreeChildren & options.subtreeClass('lldpAdjEp,lldpIf'))
```

Just wondering why I have to add `lldpIf` in the subtreeClass as I would think `lldpIf`is the root of the tree? But might be how APIC works.

Regardless thanks a lot !!!

**Comment by kprav33n** [comment]
I'm not sure what exactly you are trying to do. I'm assuming that you are retrieving LLDP adjacencies for a given port (fabric PathEp DN). This is my recommendation on how to do it.

```python
[iface] = leaf.methods.ResolveClass('lldpIf').GET(**(
    options.filter(filters.Eq('lldpIf.portDesc', 
                              'topology/pod-3/paths-1017/pathep-[eth1/23]')) & 
    options.rspSubtreeFull))
for adj in iface.lldpAdjEp:
    print(f'Adjacency {adj.id} => {adj.sysName}:{adj.portDesc}')
```
