### ISSUE TITLE
Unpinned Flask dependency breaks installation in Ubuntu after Flask 3.1.0 release updated blinker dependency

### ISSUE THREAD

**Issue by mikemccracken** [datacenter/pyaci#63]
Flask 3.1.0 was released a couple of days ago, and it includes this commit: https://github.com/pallets/flask/commit/8f37c82f6144fffc2ed30e49ee81a54702a0f317
which bumps the Flask dep of 'blinker' from 1.6.2 to 1.8 (a later commit bumps it to 1.9).

If you are on an ubuntu system that has a debian package installed version of python3-blinker, pip3 will complain like this, 
even when passed --break-system-packages:
```
ERROR: Cannot uninstall blinker 1.7.0, RECORD file not found. Hint: The package was installed by debian.
```

Ubuntu does not ship a debian package version of blinker newer than 1.9 - plucky has 1.8 and jammy has 1.7: https://packages.ubuntu.com/plucky/python3-blinker

Since cloud-init depends on python3-blinker via python3-oauthlib, this seems like it might be a common problem.

Locally we have worked around this in pyaci by pinning the Flask dep to <3.1 and the blinker dep to <1.8. 
I am not sure if this is the best fix for pyaci upstream but I wanted to bring it up for discussion.

**Comment by camrossi** [comment]
Flask dependency has been pinned to 3.0.x for the moment
